apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-postgres
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/lib/postgresql/data/pgdata/subdir && chown -R 999:999 /var/lib/postgresql/data/pgdata"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin123"
            - name: POSTGRES_DB
              value: "mydb"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata/subdir"  
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        storageClassName: azurefile
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
